QCMApp/Controllers/ElementController.cs
using QCMApp.bll;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QCMApp.Tools;

namespace QCMApp.Controllers
{
    public class ElementController : Controller
    {


        // GET: Element
        public ActionResult ElementUp(int idElement)
        {
            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("elementUp.Element.Entrée(idElement: {0})", idElement));
            Elements element = new Elements();
            try
            {

                element = DALElement.FindById(idElement);
                DALElement.elementUp(idElement);
            }
            catch (Exception e)
            {
                Tools.Logger.Ecrire(Tools.Logger.Niveau.Erreur, string.Format("elementUp.Element.Exception(Exception: {0})", e));
                ViewBag.Error = ErrorList.elementDown;
            }


            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("elementUp.Element.Sortie(idQuestionnaire: {0})", element.questionnaire_id));

            return RedirectToAction("PageCreateQuestionnaire", "Questionnaire", new { id = element.questionnaire_id });
        }
        public ActionResult ElementDown(int idElement)
        {
            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("elementUp.Element.Entrée(idElement: {0})", idElement));
            Elements element = new Elements();
            try
            {

                element = DALElement.FindById(idElement);
                DALElement.elementDown(idElement);
            }
            catch (Exception e)
            {
                Tools.Logger.Ecrire(Tools.Logger.Niveau.Erreur, string.Format("elementUp.Element.Exception(Exception: {0})", e));
                ViewBag.Error = ErrorList.elementDown;
            }


            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("elementUp.Element.Sortie(idQuestionnaire: {0})", element.questionnaire_id));

            return RedirectToAction("PageCreateQuestionnaire", "Questionnaire", new { id = element.questionnaire_id });
        }
    }
}

QCMApp/Controllers/QuestionnaireController.cs
using QCMApp.bll;
using QCMApp.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using QCMApp.Tools;

namespace QCMApp.Controllers
{
    public class QuestionnaireController : Controller
    {

        private const string _CST_DIRECTORY_IMAGE = "~/Content/images/";
        private const string _CST_DIRECTORY_VIDEO = "~/Content/videos/";


        /**
         * Méthode qui dirige vers la page listeQuestionnaire
         *
         */
        public ActionResult ListeQuestionnaires(String erreur)
        {
            ViewModelQuestionnaireSite vmqs = new ViewModelQuestionnaireSite();
            if (erreur != null)
            {
                ViewBag.Error = erreur;
            }
            try
            {
                vmqs.questionnaires = DALQuestionnaire.SelectAll();
                vmqs.sites = DALSite.SelectAllSite();
            }
            catch (Exception e)
            {
                ViewBag.Error = ErrorList.listeQuestionnaire;
                Tools.Logger.Ecrire(Tools.Logger.Niveau.Erreur, string.Format("QuestionnairesController.ListeQuestionnaires.Exception(Nombres questionnaire : {0},nombre sites : {1} message erreur : {2})", vmqs.questionnaires.Count, vmqs.sites.Count, e));

            }



            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("QuestionnairesController.ListeQuestionnaires.Sortie(Nombres questionnaire : {0},nombre sites : {1})", vmqs.questionnaires.Count, vmqs.sites.Count));
            return View(vmqs);
        }
        /**
         * Dirige vers la page de création du questionnaire
         */
        public ActionResult PageCreateIntituleQuestionnaire()
        {
            return View();
        }
        /**
         * Va créer le questionnaire juste avec l'intitulé car plus facile à gérer par la suite
         * puis dirige vers la page de création du questionnaire
         */
        public ActionResult CreateIntituleQuestionnaire(string intitule)
        {
            ViewModelQuestionnaireElements vm = new ViewModelQuestionnaireElements();
            var questionnaireEntity = new Questionnaires();
            int id = 0;
            try
            {

                questionnaireEntity.intitule = intitule;
                questionnaireEntity.date = DateTime.Now;
                questionnaireEntity.note = 16;
                questionnaireEntity.actif = false;
                DALQuestionnaire.InsertQuestionnaire(questionnaireEntity);
                id = questionnaireEntity.Id;

            }
            catch (Exception e)
            {
                Tools.Logger.Ecrire(Tools.Logger.Niveau.Erreur, string.Format("CreateIntituleQuestionnaire.Questionnaire.Exception(Questionnaire créé : {0}, exception : {1})", Tools.JsonHelper.Serialize(questionnaireEntity, typeof(Questionnaires)), e));
                return RedirectToAction("ListeQuestionnaires", "Questionnaire", new { erreur = ErrorList.intituleQuestionnaire });
            }


            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("CreateIntituleQuestionnaire.Questionnaire.Sortie(Questionnaire créé : {0})", Tools.JsonHelper.Serialize(questionnaireEntity, typeof(Questionnaires))));

            return RedirectToAction("PageCreateQuestionnaire", "Questionnaire", new { id = id });
        }

        [HttpGet]
        public ActionResult PageCreateQuestionnaire(int id, String erreur)
        {
            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("PageCreateQuestionnaire.Questionnaire.Entrée(idQuestionnaire : {0})", id));
            if (erreur != null)
            {
                ViewBag.Error = erreur;
            }

            var questionnaireEntity = new Questionnaires();
            ViewModelQuestionnaireElements vmqe = new ViewModelQuestionnaireElements();
            try
            {
                questionnaireEntity = DALQuestionnaire.FindById(id);
                vmqe.questionnaire = questionnaireEntity;
                vmqe.elements = DALElement.SelectAllFromQuestionnaire(id);


            }
            catch (Exception e)
            {
                Tools.Logger.Ecrire(Tools.Logger.Niveau.Erreur, string.Format("PageCreateQuestionnaire.Questionnaire.Exception(idQuesstionnaire : {0}, exception : {1}", id, e));
                return RedirectToAction("ListeQuestionnaires", "Questionnaire", new { erreur = ErrorList.pageCreateQuestionnaire });
            }


            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("PageCreateQuestionnaire.Questionnaire.Sortie(idQuestionnaire : {0})", id));

            return View(vmqe);
        }
        /**
         * Autre méthode en Json résult qui dirige vers la méthode PageCreatQuestionnaire
         */
        public JsonResult PageCreateQuestionnaireJquery(int id)
        {
            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("PageCreateQuestionnairJquery.Questionnaire.Entrée(idQuestionnaire : {0})", id));

            return Json(new
            {
                redirectUrl = Url.Action("PageCreateQuestionnaire", "Questionnaire", new { id = id }),
                isRedirect = true
            });
        }

        /**
         * Le questionnaire est déja créer avec la création de l'intitule et la on va ajouter le texte, la date de création
         * la note minim.
         */
        public ActionResult CreateQuestionnaireJquery(string intitule, int? note, int id)
        {
            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("CreateQuestionnaireJquery.Questionnaire.Entrée(intitule : {0},note : {1}, id : {2})", intitule, note, id));

            var questionnaireEntity = new Questionnaires();
            questionnaireEntity.intitule = intitule;
            questionnaireEntity.note = note;
            questionnaireEntity.date = DateTime.Now;
            questionnaireEntity.Id = id;
            try
            {
                DALQuestionnaire.UpdateQuestionnaire(questionnaireEntity);
            }
            catch (Exception e)
            {
                Tools.Logger.Ecrire(Tools.Logger.Niveau.Erreur, string.Format("CreateQuestionnaireJquery.Questionnaire.Exception(questionnaire : {0})", Tools.JsonHelper.Serialize(questionnaireEntity, typeof(Questionnaires))));
                return Json(new
                {
                    redirectUrl = Url.Action("ListeQuestionnaires", "Questionnaire", ErrorList.createQuestionnaireJquery),
                    isRedirect = true
                });
            }

            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("CreateQuestionnaireJquery.Questionnaire.Sortie(questionnaire : {0})", Tools.JsonHelper.Serialize(questionnaireEntity, typeof(Questionnaires))));

            return Json(new
            {
                redirectUrl = Url.Action("ListeQuestionnaires", "Questionnaire"),
                isRedirect = true
            });
        }

        public RedirectToRouteResult CopyQuestionnaire(int id)
        {
            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("CopyQuestionnaire.Questionnaire.Entrée({0})", id));
            int? newId = null;

            try
            {
                newId = DALQuestionnaire.CopyQuestionnaire(id, Server.MapPath(Tools.ConfigHelper._CST_DIRECTORY_IMAGE), Server.MapPath(Tools.ConfigHelper._CST_DIRECTORY_VIDEO));

                Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("CopyQuestionnaire.Questionnaire.Sortie(idQuestionnaire : {0})", id));

                if (newId.HasValue)
                    return RedirectToAction("PageCreateQuestionnaire", "Questionnaire", new { id = newId.Value });
                else
                    return RedirectToAction("ListeQuestionnaires", "Questionnaire");

            }
            catch (Exception e)
            {
                Tools.Logger.Ecrire(Tools.Logger.Niveau.Erreur, string.Format("CopyQuestionnaire({0})", id), e);
                return RedirectToAction("ListeQuestionnaires", "Questionnaire");
            }

        }

        /**
         * Fonction delete appelé en Jquery
         */
        public JsonResult DeleteQuestionnaireJquery(int idQuestionnaire)
        {
            Tools.Logger.Ecrire(Tools.Logger.Niveau.Info, string.Format("DeleteQuestionnaire.Questionnaire.Entrée({0})", idQuestionnaire));
            MediaController med = new MediaController();
            var pothImage = Path.Combine(Server.MapPath(_CST_DIRECTORY_IMAGE));
            var pothVideo = Path.Combine(Server.MapPath(_CST_DIRECTORY_VIDEO));

            try
            {
                var questionnaire = DALQuestionnaire.FindById(idQuestionnaire);
                if (DALElement.SelectAllQuestionFromQuestionnaire(idQuestionnaire) != null)
                {
                    var elements = DALElement.SelectAllFromQuestionnaire(idQuestionnaire);
                    foreach (var element in elements)
                    {
                        if (DALMedia.SelectAllFromElement(element.Id) != null)
                        {
                            var images = DALMedia.SelectAllFromElement(element.Id);
                            foreach (var image in images)
                            {

                                med.DeleteImage(image.Id, pothImage);
                            }
                        }

                        if (DALMedia.SelectVideoFromElement(element.Id) != null)
                        {
                            med.DeleteVideo(DALMedia.SelectVideoFromElement(element.Id).Id,pothVideo);
                        }

                        if (element.TypeElement_Id == 2)

QCMApp/Views/Questionnaire/PageCreateIntituleQuestionnaire.cshtml
@model QCMApp.Questionnaires

@{
    ViewBag.Title = "PageCreateIntituleQuestionnaire";
}
@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 messageErreur">
            <div class="text-danger">@ViewBag.Error</div>
        </div>
        <div class="col-md-3"></div>
    </div>
}

<h2 class="titrePage">Intitulé questionnaire</h2>


<h4>Questionnaires</h4>
<hr />
@using (Html.BeginForm("CreateIntituleQuestionnaire", "Questionnaire", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            <div class="row">
                <div class="col-md-4">

                </div>
                <div class="col-md-4">
                    <input type="text" class="form-control" placeholder="Intitulé du questionnaire" name="intitule" id="intituleCreateIntitule" required />
                    <input type="submit" id="saveIntitule" name="saveIntitule" value="Enregistrer l'intitulé" class="btn-primary form-control" />
                </div>
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @*<script type="text/javascript">
        $(document).ready(function() {
            $("#saveIntitule").click(function () {
                alert("Vous allez pouvoir commencer à ajouter les éléments dans le questionnaire");

                });


            }
        );*@

    @*</script>*@
}


QCMApp/Views/Questionnaire/PageCreateQuestionnaire.cshtml
@model QCMApp.Models.ViewModelQuestionnaireElements

@{
    ViewBag.Title = "CreateQuestionnaire";
}
@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 messageErreur">
            <div class="text-danger">@ViewBag.Error</div>
        </div>
        <div class="col-md-3"></div>
    </div>
    <br/>
}
<div class="row">
    <div class="col-md-4">
        <h2 class="titrePage">Création questionnaire</h2>
    </div>
    <div class="col-md-5">
        <input type="text" class="form-control" value="@Model.questionnaire.intitule" name="intituleQuestionnaire" id="intituleQuestionnaire" size="100" />
    </div>
    <div class="col-md-3">
    </div>

</div>




<table class="table">
    <tr>
        <th>
            Type
        </th>
        <th>
            Intitulé de l'élément
        </th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>

        <th>
            Actions
        </th>


        <th>Déplacer</th>
    </tr>
    @{
        var compteur = 0;
    }
    @if (Model.elements != null)
    {
        foreach (var element in Model.elements)
        {

            <tr class="@(element.TypeElement_Id == 1 ? "ligneDescription" : "ligneQuestion")">
                <td>

                    <p class="typeElement" id="@(element.TypeElement_Id == 1 ? "descriptionType" : "questionType")">
                        @(element.TypeElement_Id == 1 ? "Description" : "Question")
                    </p>

                </td>
                <td>
                    @element.intitule
                </td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>

                <td>
                    @if (element.TypeElement_Id == 1)
                    {
                        <input type="button" class="btn btn-outline-primary" value="Update" onclick="location.href='@Url.Action("PageUpdateDescription", "Description", new { idElement = element.Id})'" />
                        <input type="button" class="btn btn-outline-primary" value="Delete" onclick="location.href='@Url.Action("DeleteElement", "Description", new { id = element.Id })'" />
                    }
                    else
                    {
                        <input type="button" class="btn btn-outline-primary" value="Update" onclick="location.href='@Url.Action("PageUpdateQuestion", "Question", new { idElement = element.Id})'" />
                        <input type="button" class="btn btn-outline-primary" value="Delete" onclick="location.href='@Url.Action("DeleteQuestion", "Question", new { id = element.Id })'" />
                    }



                </td>

                <th>
                    @if (compteur == 0)
                    {
                        @*<input type="button" class="btn btn-light" value="+" onclick="location.href='@Url.Action("ElementDown", "Element", new { idElement = element.Id })'" />*@
                        <input class="arrowButton" type="hidden" />
                        <input class="rounded arrowButton border border-primary" type="image"
                               src="~/Content/asserts/icones/fleche_down.png"
                               onclick="location.href='@Url.Action("ElementDown", "Element", new { idElement = element.Id })'" />
                        compteur++;
                    }
                    else if (compteur != Model.elements.Count - 1)
                    {
                        @*<input type="button" class="btn btn-light" value="-" onclick="location.href='@Url.Action("ElementUp", "Element", new { idElement = element.Id })'" />
                            <input type="button" class="btn btn-light" value="+" onclick="location.href='@Url.Action("ElementDown", "Element", new { idElement = element.Id })'" />*@
                        @*<input type="button" style="background: url(~/Content/asserts/open-iconic/svg/arrow-thick-bottom.svg)" class="btn btn-light" value="+" onclick="location.href='@Url.Action("ElementDown", "Element", new { idElement = element.Id })'" />
                            <img src="~/Content/asserts/open-iconic/svg/arrow-thick-bottom.svg"  onclick="location.href='@Url.Action("ElementDown", "Element", new { idElement = element.Id })'"  alt="icon name">*@
                        <input class="rounded arrowButton border border-primary" type="image"
                               src="~/Content/asserts/icones/fleche_down.png"
                               onclick="location.href='@Url.Action("ElementDown", "Element", new { idElement = element.Id })'" />
                        <input class="rounded arrowButton border border-primary" type="image"
                               src="~/Content/asserts/icones/fleche_haut.png"
                               onclick="location.href='@Url.Action("ElementUp", "Element", new { idElement = element.Id })'" />

                        compteur++;
                    }
                    else
                    {
                        <input class="rounded arrowButton border border-primary" type="image"
                               src="~/Content/asserts/icones/fleche_haut.png"
                               onclick="location.href='@Url.Action("ElementUp", "Element", new { idElement = element.Id })'" />
                    }

                </th>

            </tr>
        }
    }
</table>

@*@if (Model.elements != null)
    {
        foreach (var element in Model.elements)
        {
            <div class="row">
                <div class="col-mid-3">
                    <h2>@element.intitule</h2>
                </div>
            </div>

        }

    }
    <div class="row">
        <div class="col-mid-3">

        </div>
    </div>*@

<hr class="style1" />

<div class="row">
    <div class="col-md-2">
        <br />
        <br />

        @*@Html.ActionLink("Nouvelle question", "", "Question", null, new { @class = "btn btn-default" })*@
        <input type="button" name="newQuestion" id="newQuestion" class="btn btn-outline-primary" value="Nouvelle question" onclick="location.href='@Url.Action("PageCreateQuestion", "Question", new { idQuestionnaire = Model.questionnaire.Id })'" />
    </div>
    <div class="col-md-2">
        <br />
        <br />
        @*@Html.ActionLink("Nouvelle description", "PageCreateDescription", "Element", new { id = Model.questionnaire.Id }, new { @class = "btn btn-default" })*@
        <input type="button" class="btn btn-outline-primary" value="Nouvelle description" onclick="location.href='@Url.Action("PageCreateDescription", "Description", new { id = Model.questionnaire.Id })'" />
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
        <br />
        <label for="note" style="font-size: small"> Note acceptable sur 20</label>
        <input type="number" class="form-control" value="@Model.questionnaire.note" name="noteQuestionnaire" id="noteQuestionnaire" min="1" max="20" />
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-1">
        <br />
        <br />
        <input type="submit" value="Enregister" id="saveQuestionnaire" onclick="fonctionSaveQuestionnaire()" class="btn btn-outline-primary" />
    </div>
    <div class="col-md-1" id="nombreQuestions">
        <br />
        <p style="font-size: small">Qts</p>
        @{
            var compteurQuestion = 0;
        }
        @foreach (var element in Model.elements)
        {
            if (element.TypeElement_Id == 2)
            {
                compteurQuestion++;
            }

        }
        <p>@compteurQuestion</p>
    </div>
    <input type="hidden" value="@Html.DisplayFor(model => model.questionnaire.Id)" name="id" id="id" />
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

        function fonctionSaveQuestionnaire() {
            var intitule = $("#intituleQuestionnaire").val();
            var note = $("#noteQuestionnaire").val();
            var idQuestionnaire = $("#id").val();

            $.post({
                url: '@Url.Action("CreateQuestionnaireJquery", "Questionnaire")',
                tpe: 'POST',
                dataType: 'json',
                data: JSON.stringify({
                    intitule : intitule,
                    note: note,
                    id : idQuestionnaire

                }),
                contentType: 'application/json; charset=utf-8',
                success: function (json) {
                    if (json.isRedirect) {
                        window.location.href = json.redirectUrl;
                    }
                }

            });
        }


    </script>
}