QCMApp/Controllers/UtilisateurController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QCMApp.bll;

namespace QCMApp.Controllers
{
    public class UtilisateurController : Controller
    {
        // GET: Utilisateur
        public ActionResult ListeUtilisateurs()
        {
            
            return View(DALUtilisateur.SelectAllUtilisateurs());
        }
    }
}

QCMApp/Views/Shared/UploadImage.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UploadImage</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

QCMApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">*@
    @*<link rel="stylesheet" href="~/Content/bootstrap.min.css" />*@
    <!-- JS, Popper.js, and jQuery -->
    @*<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>*@
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="icon" href="~/Content/asserts/logo/favicon.jpeg" />
</head>
<body>

    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Questionnaires", "ListeQuestionnaires", "Questionnaire")</li>
                    <li>@Html.ActionLink("Utilisateurs", "ListeUtilisateurs", "Utilisateur")</li>
                </ul>
            </div>
        </div>
    </div>*@

        <nav class="navbar navbar-expand-lg navbar-light bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav navbar-nav">
                    <li class="nav-item active">
                        <input type="button" class="btn btn-outline-primary" value="Accueil" onclick="location.href='@Url.Action("Index", "Home")'" />
                    </li>

                    <li class="nav-item">
                        <input type="button" class="btn btn-outline-primary" value="Questionnaires" onclick="location.href='@Url.Action("ListeQuestionnaires", "Questionnaire")'" />
                    </li>
                    <li class="nav-item">
                        <input type="button" class="btn btn-outline-primary" value="Utilisateurs" onclick="location.href='@Url.Action("ListeUtilisateurs", "Utilisateur")'" />
                    </li>
                </ul>
            </div>
        </nav>

    <div class="container body-content" id="leBody">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Application QCM</p>
            <input type="button" name="name" value="Try again" onclick="location.href = '@Url.Action("Refresh", "UserQuestionnaire")'" />

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>